# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy PHP app to Azure Web App - petcare

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # Requerido para el login de Azure v√≠a OIDC
      contents: read    # Requerido para acciones de checkout

    steps:
      - name: üì¶ Checkout code
        uses: actions/checkout@v4

      - name: üõ†Ô∏è Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: üîç Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'composer.json'

      - name: üî® Run composer install
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          composer validate --no-check-publish
          composer install --prefer-dist --no-progress --ignore-platform-req=ext-grpc

      - name: üîê Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_799FCD3045EF48E1A3020CDD43B6004E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4AF846A85DC745FBAAE8249F0A104510 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9E09A42517A040A58E2F79EA1CBD40BE }}

      - name: üöÄ Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'petcare'
          slot-name: 'Production'
          package: .
